storyteller-api-message: StoryTellerAPI
random-image-ms-message: RandomImageMicroService
random-story-ms-message: RandomStoryMicroService
some: thing

logging:
# file: /var/memento/security.log
  level:
    com.codependent: 'INFO'
eureka:
  client:
    healthcheck:
      enabled: true
      
finder: 
 stories:
  -
    author: Antony
    content: "a story by Antony"
    id: 1
    name: "My Story"
  -
    author: Nagameena
    content: "a story by Antony"
    id: 2
    name: "My Story"
