storyteller-api-message: StoryTellerAPI
random-image-ms-message: RandomImageMicroService
random-story-ms-message: RandomStoryMicroService
some: something new

logging:
# file: /var/memento/security.log
  level:
    com.codependent: 'INFO'
eureka:
  client:
    healthcheck:
      enabled: true
